### ISSUE TITLE
gcc: error: mcd/metrics_fast.c: No such file or directory

### ISSUE THREAD

**Issue by pineking** [MattShannon/mcd#5]
when run the command: 
python setup.py build_ext --inplace

The Error shows that:

running build_ext
building 'mcd.metrics_fast' extension
creating build
creating build/temp.linux-x86_64-2.6
creating build/temp.linux-x86_64-2.6/mcd
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.6 -c mcd/metrics_fast.c -o build/temp.linux-x86_64-2.6/mcd/metrics_fast.o -Wno-unused-but-set-variable -O3
gcc: error: mcd/metrics_fast.c: No such file or directory
gcc: fatal error: no input files
compilation terminated.
error: command 'gcc' failed with exit status 1

**Comment by MattShannon** [comment]
@pineking Sorry the exceedingly slow reply! If you ever worked out what the issue was then I'd love to hear from you. The command you used should generate metrics_fast.c from metrics_fast.pyx if it needs to be generated, so the error message seems surprising.

**Comment by pineking** [comment]
@MattShannon yes, I had solved this issue. Thank you.
