### ISSUE TITLE
A question about the meaning of mcd calculation

### ISSUE THREAD

**Issue by xiaodaxia** [MattShannon/mcd#6]
I am quite new to voice research. I would like to know why when you compute mcd from mel-cepstrum, you ignore the 0th component. Can you give a reference or more explanation about it.   
mcd/bin/get_mcd_dtw at Line75:
        
        # ignore 0th cepstral component
        nat = nat[:, 1:]
        synth = synth[:, 1:]

**Comment by MattShannon** [comment]
Sure, see Kubichek's paper (Mel-cepstral distance measure for objective speech quality assessment). I believe the idea is that the component 0 is energy-related, whereas components 1, 2, ... are related to spectral shape, and it makes some sense to say you don't care about overall energy.
